import { BlogPost, Bus, Company } from '@/types';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Autocares Barcelona Premium',
    logo: '/images/companies/autocares-barcelona-premium.png',
    rating: 4.8,
    reviewCount: 342,
    verified: true,
    description: 'Empresa líder en transporte de pasajeros con más de 25 años de experiencia en Catalunya.',
    fleet: [],
  },
  {
    id: '2',
    name: 'Costa Brava Tours',
    logo: '/images/companies/costa-brava-tours.png',
    rating: 4.6,
    reviewCount: 218,
    verified: true,
    description: 'Especialistas en excursiones y eventos corporativos por toda la Costa Brava.',
    fleet: [],
  },
  {
    id: '3',
    name: 'Transports Modernos SA',
    logo: '/images/companies/transports-modernos-sa.png',
    rating: 4.7,
    reviewCount: 456,
    verified: true,
    description: 'Flota moderna con autobuses de última generación y conductores profesionales.',
    fleet: [],
  },
  {
    id: '4',
    name: 'Autocares Cataluña Express',
    logo: '/images/companies/autocares-express.png',
    rating: 4.5,
    reviewCount: 189,
    verified: true,
    description: 'Servicios de transporte para bodas, eventos y viajes escolares.',
    fleet: [],
  },
];

export const mockBuses: Bus[] = [
  {
    id: '1',
    companyId: '1',
    name: 'Mercedes Tourismo Premium',
    capacity: 55,
    type: 'luxury',
    amenities: ['WiFi', 'Aire acondicionado', 'Asientos reclinables', 'WC', 'USB', 'Pantallas individuales'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    pricePerDay: 850,
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: '2',
    companyId: '1',
    name: 'Setra Comfort Class',
    capacity: 49,
    type: 'standard',
    amenities: ['WiFi', 'Aire acondicionado', 'Asientos reclinables', 'USB'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    pricePerDay: 650,
    rating: 4.7,
    reviewCount: 62,
  },
  {
    id: '3',
    companyId: '2',
    name: 'Minibús Mercedes Sprinter',
    capacity: 19,
    type: 'minibus',
    amenities: ['Aire acondicionado', 'Asientos cómodos', 'Espacio para equipaje'],
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
    ],
    pricePerDay: 380,
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: '4',
    companyId: '3',
    name: 'Volvo 9700 Premium',
    capacity: 53,
    type: 'luxury',
    amenities: ['WiFi', 'Aire acondicionado', 'Asientos reclinables', 'WC', 'USB', 'Cafetera', 'Nevera'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    pricePerDay: 920,
    rating: 4.8,
    reviewCount: 103,
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Cómo organizar el transporte perfecto para tu boda',
    excerpt: 'Consejos prácticos para elegir el autocar ideal y garantizar que todos tus invitados lleguen cómodos y puntuales.',
    image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
    author: 'María García',
    date: '2024-10-15',
    slug: 'organizar-transporte-boda',
    category: 'Bodas',
  },
  {
    id: '2',
    title: 'Beneficios de viajar en autocar para excursiones escolares',
    excerpt: 'Por qué el autocar es la opción más segura y económica para viajes de estudiantes.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    author: 'Carlos Rodríguez',
    date: '2024-10-20',
    slug: 'excursiones-escolares-autocar',
    category: 'Educación',
  },
  {
    id: '3',
    title: 'Sostenibilidad: El autocar como transporte ecológico',
    excerpt: 'Descubre cómo viajar en grupo reduce la huella de carbono y contribuye al medio ambiente.',
    image: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b0?w=800',
    author: 'Laura Martínez',
    date: '2024-10-25',
    slug: 'sostenibilidad-autocar',
    category: 'Sostenibilidad',
  },
];
